vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.g.colors_name = "honeynil"
vim.o.termguicolors = true

local c = {
  black      = "#1A1D23",
  dark       = "#2E3440",
  dark2      = "#3B4252",
  gray       = "#4C566A",
  gray_mid   = "#9099A5",
  light_gray = "#D8DEE9",
  lighter    = "#E5E9F0",
  white      = "#ECEFF4",
  honey_dark   = "#7A4A0A",
  honey        = "#B8720E",
  honey_bright = "#E09832",
  honey_light  = "#F5C55A",
  honey_pale   = "#FBE8B0",
  red    = "#BF616A",
  orange = "#D08770",
  yellow = "#EBCB8B",
  green  = "#A3BE8C",
  teal   = "#8FBCBB",
  blue   = "#81A1C1",
  purple = "#B48EAD",
  none   = "NONE",
}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hl("Normal",         { fg = c.light_gray, bg = c.black })
hl("NormalFloat",    { fg = c.light_gray, bg = c.dark })
hl("NormalNC",       { fg = c.light_gray, bg = c.black })
hl("FloatBorder",    { fg = c.honey_bright, bg = c.dark })
hl("FloatTitle",     { fg = c.honey_bright, bold = true })
hl("Cursor",         { fg = c.black, bg = c.honey_bright })
hl("CursorLine",     { bg = c.dark })
hl("CursorColumn",   { bg = c.dark })
hl("CursorLineNr",   { fg = c.honey_bright, bold = true })
hl("LineNr",         { fg = c.gray })
hl("SignColumn",     { bg = c.black })
hl("ColorColumn",    { bg = c.dark })
hl("VertSplit",      { fg = c.dark2 })
hl("WinSeparator",   { fg = c.dark2 })
hl("StatusLine",     { fg = c.light_gray, bg = c.dark })
hl("StatusLineNC",   { fg = c.gray, bg = c.dark })
hl("MsgArea",        { fg = c.light_gray, bg = c.black })

hl("Pmenu",      { fg = c.light_gray, bg = c.dark2 })
hl("PmenuSel",   { fg = c.black, bg = c.honey_bright, bold = true })
hl("PmenuSbar",  { bg = c.dark2 })
hl("PmenuThumb", { bg = c.honey })
hl("CmpPmenu",   { fg = c.light_gray, bg = c.dark2 })
hl("CmpDoc",     { fg = c.light_gray, bg = c.dark })

hl("TabLine",     { fg = c.gray_mid, bg = c.dark })
hl("TabLineSel",  { fg = c.honey_bright, bg = c.black, bold = true })
hl("TabLineFill", { bg = c.dark })

hl("Search",     { fg = c.black, bg = c.honey_light })
hl("IncSearch",  { fg = c.black, bg = c.honey_bright, bold = true })
hl("CurSearch",  { fg = c.black, bg = c.honey_bright, bold = true })
hl("Visual",     { bg = c.dark2 })
hl("VisualNOS",  { bg = c.dark2 })
hl("MatchParen", { fg = c.honey_bright, bold = true, underline = true })

hl("NonText",     { fg = c.gray })
hl("Whitespace",  { fg = c.dark2 })
hl("SpecialKey",  { fg = c.gray })
hl("Folded",      { fg = c.gray_mid, bg = c.dark, italic = true })
hl("FoldColumn",  { fg = c.gray, bg = c.black })
hl("Directory",   { fg = c.blue })
hl("Title",       { fg = c.honey_bright, bold = true })
hl("EndOfBuffer", { fg = c.dark2 })
hl("Question",    { fg = c.honey_bright })
hl("MoreMsg",     { fg = c.green })
hl("WarningMsg",  { fg = c.yellow })
hl("ErrorMsg",    { fg = c.red, bold = true })
hl("WildMenu",    { fg = c.black, bg = c.honey_bright })

hl("DiagnosticError",          { fg = c.red })
hl("DiagnosticWarn",           { fg = c.yellow })
hl("DiagnosticInfo",           { fg = c.blue })
hl("DiagnosticHint",           { fg = c.teal })
hl("DiagnosticOk",             { fg = c.green })
hl("DiagnosticVirtualTextError",{ fg = c.red,    italic = true })
hl("DiagnosticVirtualTextWarn", { fg = c.yellow, italic = true })
hl("DiagnosticVirtualTextInfo", { fg = c.blue,   italic = true })
hl("DiagnosticVirtualTextHint", { fg = c.teal,   italic = true })
hl("DiagnosticUnderlineError",  { undercurl = true, sp = c.red })
hl("DiagnosticUnderlineWarn",   { undercurl = true, sp = c.yellow })
hl("DiagnosticUnderlineInfo",   { undercurl = true, sp = c.blue })
hl("DiagnosticUnderlineHint",   { undercurl = true, sp = c.teal })
hl("DiagnosticSignError", { fg = c.red })
hl("DiagnosticSignWarn",  { fg = c.yellow })
hl("DiagnosticSignInfo",  { fg = c.blue })
hl("DiagnosticSignHint",  { fg = c.teal })

hl("Comment",        { fg = c.gray,       italic = true })
hl("Constant",       { fg = c.honey_light })
hl("String",         { fg = c.green })
hl("Character",      { fg = c.green })
hl("Number",         { fg = c.honey_bright })
hl("Boolean",        { fg = c.honey_bright, bold = true })
hl("Float",          { fg = c.honey_bright })
hl("Identifier",     { fg = c.light_gray })
hl("Function",       { fg = c.honey_bright, bold = true })
hl("Statement",      { fg = c.blue })
hl("Keyword",        { fg = c.blue })
hl("Conditional",    { fg = c.blue,  bold = true })
hl("Repeat",         { fg = c.blue,  bold = true })
hl("Label",          { fg = c.blue })
hl("Operator",       { fg = c.teal })
hl("Exception",      { fg = c.red,   bold = true })
hl("PreProc",        { fg = c.teal })
hl("Include",        { fg = c.teal })
hl("Define",         { fg = c.teal })
hl("Macro",          { fg = c.teal })
hl("PreCondit",      { fg = c.teal })
hl("Type",           { fg = c.honey_light })
hl("StorageClass",   { fg = c.blue })
hl("Structure",      { fg = c.honey_light })
hl("Typedef",        { fg = c.honey_light })
hl("Special",        { fg = c.honey_bright })
hl("SpecialChar",    { fg = c.honey_bright })
hl("Tag",            { fg = c.honey_bright })
hl("Delimiter",      { fg = c.gray_mid })
hl("SpecialComment", { fg = c.gray,   italic = true })
hl("Underlined",     { underline = true })
hl("Bold",           { bold = true })
hl("Italic",         { italic = true })
hl("Error",          { fg = c.red })
hl("Todo",           { fg = c.black, bg = c.honey_bright, bold = true })

hl("@variable",               { fg = c.light_gray })
hl("@variable.builtin",       { fg = c.teal,        italic = true })
hl("@variable.parameter",     { fg = c.orange })
hl("@variable.member",        { fg = c.light_gray })
hl("@constant",               { fg = c.honey_light })
hl("@constant.builtin",       { fg = c.honey_bright, bold = true })
hl("@constant.macro",         { fg = c.honey_bright })
hl("@module",                 { fg = c.teal })
hl("@module.builtin",         { fg = c.teal,         bold = true })
hl("@label",                  { fg = c.blue })
hl("@string",                 { fg = c.green })
hl("@string.escape",          { fg = c.honey_bright })
hl("@string.special",         { fg = c.honey_light })
hl("@string.special.url",     { fg = c.blue,         underline = true })
hl("@character",              { fg = c.green })
hl("@number",                 { fg = c.honey_bright })
hl("@number.float",           { fg = c.honey_bright })
hl("@boolean",                { fg = c.honey_bright, bold = true })
hl("@function",               { fg = c.honey_bright, bold = true })
hl("@function.builtin",       { fg = c.honey_light })
hl("@function.call",          { fg = c.honey_bright })
hl("@function.method",        { fg = c.honey_bright, bold = true })
hl("@function.method.call",   { fg = c.honey_bright })
hl("@constructor",            { fg = c.honey_light })
hl("@operator",               { fg = c.teal })
hl("@keyword",                { fg = c.blue })
hl("@keyword.function",       { fg = c.blue,         bold = true })
hl("@keyword.return",         { fg = c.blue,         bold = true })
hl("@keyword.operator",       { fg = c.teal })
hl("@keyword.import",         { fg = c.teal })
hl("@keyword.type",           { fg = c.blue })
hl("@keyword.modifier",       { fg = c.blue,         italic = true })
hl("@keyword.repeat",         { fg = c.blue,         bold = true })
hl("@keyword.conditional",    { fg = c.blue,         bold = true })
hl("@keyword.exception",      { fg = c.red,          bold = true })
hl("@type",                   { fg = c.honey_light })
hl("@type.builtin",           { fg = c.honey,        italic = true })
hl("@type.definition",        { fg = c.honey_light,  bold = true })
hl("@attribute",              { fg = c.teal })
hl("@property",               { fg = c.light_gray })
hl("@comment",                { fg = c.gray,         italic = true })
hl("@comment.todo",           { fg = c.black, bg = c.honey_bright, bold = true })
hl("@comment.warning",        { fg = c.black, bg = c.yellow,       bold = true })
hl("@comment.error",          { fg = c.black, bg = c.red,          bold = true })
hl("@punctuation.bracket",    { fg = c.gray_mid })
hl("@punctuation.delimiter",  { fg = c.gray_mid })
hl("@punctuation.special",    { fg = c.teal })
hl("@tag",                    { fg = c.honey_bright })
hl("@tag.attribute",          { fg = c.orange })
hl("@tag.delimiter",          { fg = c.gray_mid })

hl("@lsp.type.namespace",     { fg = c.teal })
hl("@lsp.type.type",          { fg = c.honey_light })
hl("@lsp.type.class",         { fg = c.honey_light })
hl("@lsp.type.struct",        { fg = c.honey_light })
hl("@lsp.type.interface",     { fg = c.honey_light,  italic = true })
hl("@lsp.type.enum",          { fg = c.honey_light })
hl("@lsp.type.enumMember",    { fg = c.honey_bright })
hl("@lsp.type.function",      { fg = c.honey_bright, bold = true })
hl("@lsp.type.method",        { fg = c.honey_bright, bold = true })
hl("@lsp.type.variable",      { fg = c.light_gray })
hl("@lsp.type.parameter",     { fg = c.orange })
hl("@lsp.type.property",      { fg = c.light_gray })
hl("@lsp.type.keyword",       { fg = c.blue })
hl("@lsp.type.comment",       { fg = c.gray, italic = true })
hl("@lsp.type.number",        { fg = c.honey_bright })
hl("@lsp.type.string",        { fg = c.green })
hl("@lsp.type.operator",      { fg = c.teal })
hl("@lsp.mod.readonly",       { italic = true })
hl("@lsp.mod.deprecated",     { strikethrough = true })

hl("LspReferenceText",               { bg = c.dark2 })
hl("LspReferenceRead",               { bg = c.dark2 })
hl("LspReferenceWrite",              { bg = c.dark2, underline = true })
hl("LspSignatureActiveParameter",    { fg = c.honey_bright, bold = true })
hl("LspInlayHint",                   { fg = c.gray, italic = true })

hl("TelescopeNormal",         { fg = c.light_gray, bg = c.dark })
hl("TelescopeBorder",         { fg = c.honey_bright, bg = c.dark })
hl("TelescopePromptNormal",   { fg = c.white, bg = c.dark2 })
hl("TelescopePromptBorder",   { fg = c.honey_bright, bg = c.dark2 })
hl("TelescopePromptPrefix",   { fg = c.honey_bright })
hl("TelescopePromptCounter",  { fg = c.honey_light })
hl("TelescopePromptCaret",    { fg = c.honey_bright, bold = true })
hl("TelescopePromptTitle",    { fg = c.black, bg = c.honey_bright, bold = true })
hl("TelescopePreviewTitle",   { fg = c.black, bg = c.honey })
hl("TelescopeResultsTitle",   { fg = c.black, bg = c.honey_dark })
hl("TelescopeSelection",      { bg = c.dark2, fg = c.honey_light })
hl("TelescopeSelectionCaret", { fg = c.honey_bright })
hl("TelescopeMatching",       { fg = c.honey_bright, bold = true })
hl("TelescopePreviewLine",    { bg = c.dark2 })
hl("TelescopePreviewMatch",   { fg = c.honey_bright, bold = true })

hl("NeoTreeNormal",            { fg = c.light_gray, bg = c.dark })
hl("NeoTreeNormalNC",          { fg = c.light_gray, bg = c.dark })
hl("NeoTreeWinSeparator",      { fg = c.dark2, bg = c.dark })
hl("NeoTreeRootName",          { fg = c.honey_bright, bold = true })
hl("NeoTreeDirectoryName",     { fg = c.blue })
hl("NeoTreeDirectoryIcon",     { fg = c.honey_bright })
hl("NeoTreeFileName",          { fg = c.light_gray })
hl("NeoTreeFileNameOpened",    { fg = c.honey_bright })
hl("NeoTreeIndentMarker",      { fg = c.dark2 })
hl("NeoTreeExpander",          { fg = c.gray })
hl("NeoTreeGitAdded",          { fg = c.green })
hl("NeoTreeGitConflict",       { fg = c.red,    bold = true })
hl("NeoTreeGitDeleted",        { fg = c.red })
hl("NeoTreeGitIgnored",        { fg = c.gray })
hl("NeoTreeGitModified",       { fg = c.yellow })
hl("NeoTreeGitUntracked",      { fg = c.orange })
hl("NeoTreeGitStaged",         { fg = c.green })
hl("NeoTreeTitleBar",          { fg = c.black, bg = c.honey_bright, bold = true })

hl("GitSignsAdd",             { fg = c.green })
hl("GitSignsChange",          { fg = c.yellow })
hl("GitSignsDelete",          { fg = c.red })
hl("GitSignsAddNr",           { fg = c.green })
hl("GitSignsChangeNr",        { fg = c.yellow })
hl("GitSignsDeleteNr",        { fg = c.red })
hl("GitSignsAddLn",           { bg = "#2b3a2b" })
hl("GitSignsChangeLn",        { bg = "#3a3520" })
hl("GitSignsDeleteLn",        { bg = "#3a2020" })
hl("GitSignsCurrentLineBlame",{ fg = c.gray, italic = true })

hl("WhichKey",        { fg = c.honey_bright })
hl("WhichKeyGroup",   { fg = c.honey_light })
hl("WhichKeyDesc",    { fg = c.light_gray })
hl("WhichKeyBorder",  { fg = c.honey_bright })
hl("WhichKeySep",     { fg = c.gray })
hl("WhichKeyFloat",   { bg = c.dark })
hl("WhichKeyValue",   { fg = c.gray_mid })

hl("IblIndent",    { fg = c.dark2 })
hl("IblScope",     { fg = c.honey })
hl("IblWhitespace",{ fg = c.dark2 })

hl("SnacksDashboardHeader",   { fg = c.honey_bright, bold = true })
hl("SnacksDashboardTitle",    { fg = c.honey_light })
hl("SnacksDashboardDesc",     { fg = c.light_gray })
hl("SnacksDashboardKey",      { fg = c.honey_bright, bold = true })
hl("SnacksDashboardIcon",     { fg = c.honey })
hl("SnacksDashboardSpecial",  { fg = c.honey_dark })
hl("SnacksDashboardFooter",   { fg = c.gray, italic = true })
hl("SnacksDashboardDir",      { fg = c.gray_mid })

hl("CmpItemAbbr",             { fg = c.light_gray })
hl("CmpItemAbbrMatch",        { fg = c.honey_bright, bold = true })
hl("CmpItemAbbrMatchFuzzy",   { fg = c.honey_bright, bold = true })
hl("CmpItemAbbrDeprecated",   { fg = c.gray, strikethrough = true })
hl("CmpItemKind",             { fg = c.honey })
hl("CmpItemKindFunction",     { fg = c.honey_bright })
hl("CmpItemKindMethod",       { fg = c.honey_bright })
hl("CmpItemKindVariable",     { fg = c.light_gray })
hl("CmpItemKindKeyword",      { fg = c.blue })
hl("CmpItemKindInterface",    { fg = c.honey_light })
hl("CmpItemKindStruct",       { fg = c.honey_light })
hl("CmpItemKindModule",       { fg = c.teal })
hl("CmpItemMenu",             { fg = c.gray_mid, italic = true })

hl("NotifyERRORBorder", { fg = c.red })
hl("NotifyWARNBorder",  { fg = c.yellow })
hl("NotifyINFOBorder",  { fg = c.blue })
hl("NotifyDEBUGBorder", { fg = c.gray })
hl("NotifyERRORIcon",   { fg = c.red })
hl("NotifyWARNIcon",    { fg = c.yellow })
hl("NotifyINFOIcon",    { fg = c.blue })
hl("NotifyERRORTitle",  { fg = c.red,    bold = true })
hl("NotifyWARNTitle",   { fg = c.yellow, bold = true })
hl("NotifyINFOTitle",   { fg = c.blue,   bold = true })
hl("NotifyERRORBody",   { fg = c.light_gray, bg = c.dark })
hl("NotifyWARNBody",    { fg = c.light_gray, bg = c.dark })
hl("NotifyINFOBody",    { fg = c.light_gray, bg = c.dark })

hl("BufferLineFill",              { bg = c.dark })
hl("BufferLineBackground",        { fg = c.gray_mid, bg = c.dark })
hl("BufferLineSelected",          { fg = c.honey_bright, bg = c.black, bold = true })
hl("BufferLineIndicatorSelected", { fg = c.honey_bright, bg = c.black })
hl("BufferLineSeparator",         { fg = c.dark2, bg = c.dark })
hl("BufferLineSeparatorSelected", { fg = c.honey_bright, bg = c.black })
hl("BufferLineModified",          { fg = c.yellow, bg = c.dark })
hl("BufferLineModifiedSelected",  { fg = c.yellow, bg = c.black })
hl("BufferLineError",             { fg = c.red, bg = c.dark })
hl("BufferLineWarning",           { fg = c.yellow, bg = c.dark })
hl("BufferLineHint",              { fg = c.teal, bg = c.dark })
hl("BufferLineInfo",              { fg = c.blue, bg = c.dark })
