return {
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
    },
    cmd  = "Neotree",
    keys = {
      { "<leader>e", "<cmd>Neotree reveal toggle left<cr>", desc = "Explorer" },
      { "<leader>o", "<cmd>Neotree focus reveal left<cr>",  desc = "Focus Explorer" },
    },
    opts = {
      close_if_last_window = false,
      popup_border_style   = "rounded",
      enable_git_status    = true,
      enable_diagnostics   = true,
      sources              = { "filesystem", "buffers", "git_status" },
      source_selector = {
        winbar         = true,
        content_layout = "center",
        separator      = { left = "", right = "" },
        sources = {
          { source = "filesystem",  display_name = " Files " },
          { source = "buffers",     display_name = " Bufs "  },
          { source = "git_status",  display_name = "  Git "   },
        },
      },
      default_component_configs = {
        container = { enable_character_fade = true },
        indent = {
          indent_size         = 2,
          padding             = 1,
          with_markers        = true,
          indent_marker       = "|",
          last_indent_marker  = "`",
          highlight           = "NeoTreeIndentMarker",
          with_expanders      = true,
          expander_collapsed  = ">",
          expander_expanded   = "v",
          expander_highlight  = "NeoTreeExpander",
        },
        icon = {
          folder_closed = "[d]",
          folder_open   = "[D]",
          folder_empty  = "[e]",
          default       = "[f]",
          highlight     = "NeoTreeFileIcon",
        },
        modified = { symbol = "[+]", highlight = "NeoTreeModified" },
        name = {
          trailing_slash    = false,
          use_git_status_colors = true,
          highlight         = "NeoTreeFileName",
        },
        git_status = {
          symbols = {
            added     = "+",
            modified  = "~",
            deleted   = "-",
            renamed   = "R",
            untracked = "?",
            ignored   = "I",
            unstaged  = "U",
            staged    = "S",
            conflict  = "C",
          },
        },
        diagnostics = {
          symbols = {
            hint  = "H",
            info  = "I",
            warn  = "W",
            error = "E",
          },
          highlights = {
            hint  = "DiagnosticSignHint",
            info  = "DiagnosticSignInfo",
            warn  = "DiagnosticSignWarn",
            error = "DiagnosticSignError",
          },
        },
      },
      window = {
        position = "left",
        width    = 36,
        mapping_options = { noremap = true, nowait = true },
        mappings = {
          ["<space>"] = { "toggle_node", nowait = false },
          ["<cr>"]    = "open",
          ["o"]       = "open",
          ["<esc>"]   = "cancel",
          ["P"]       = { "toggle_preview", config = { use_float = true, use_image_nvim = true } },
          ["l"]       = "focus_preview",
          ["S"]       = "open_split",
          ["s"]       = "open_vsplit",
          ["t"]       = "open_tabnew",
          ["w"]       = "open_with_window_picker",
          ["C"]       = "close_node",
          ["z"]       = "close_all_nodes",
          ["a"]       = { "add", config = { show_path = "none" } },
          ["A"]       = "add_directory",
          ["d"]       = "delete",
          ["r"]       = "rename",
          ["y"]       = "copy_to_clipboard",
          ["x"]       = "cut_to_clipboard",
          ["p"]       = "paste_from_clipboard",
          ["c"]       = "copy",
          ["m"]       = "move",
          ["q"]       = "close_window",
          ["R"]       = "refresh",
          ["?"]       = "show_help",
          ["<"]       = "prev_source",
          [">"]       = "next_source",
          ["i"]       = "show_file_details",
        },
      },
      filesystem = {
        filtered_items = {
          visible         = false,
          hide_dotfiles   = false,
          hide_gitignored = false,
          hide_hidden     = false,
          never_show      = { ".DS_Store", "thumbs.db" },
        },
        follow_current_file  = { enabled = true },
        group_empty_dirs     = false,
        hijack_netrw_behavior = "open_default",
        use_libuv_file_watcher = false,
      },
      buffers = {
        follow_current_file = { enabled = true },
        show_unloaded        = true,
      },
      git_status = {
        window = {
          position = "float",
          mappings = {
            ["A"]  = "git_add_all",
            ["gu"] = "git_unstage_file",
            ["ga"] = "git_add_file",
            ["gr"] = "git_revert_file",
            ["gc"] = "git_commit",
            ["gp"] = "git_push",
            ["gg"] = "git_commit_and_push",
            ["o"]  = { "show_help", nowait = false, config = { title = "Order by", prefix_key = "o" }},
          },
        },
      },
    },
  },
}
